### ISSUE TITLE
root-6.00.02 has $PORTAGE_TMPDIR in config files

### ISSUE THREAD

**Issue by jlec** [gentoo-science/sci#238]
in many of the files in /etc/root there is a reference to the portage user HOME. This needs to be removed.

**Comment by bircoph** [comment]
Hmm, the same problem with 5.34.26.
To make it worse, precompiled header contain hardcoded paths too, so sed is not a solution here.

**Comment by bircoph** [comment]
Oh, it's ok with 5.34.26, checked on a host with 6.x by mistake.

**Comment by bircoph** [comment]
Fixed in 6.02.05-r2.

Please note that allDict.cxx.pch file still contains $PORTAGE_TMPDIR (as well as each *.so in /usr/lib/root). This can't be helped. Generated PCH file is relocatable, so this is not an issue. The only way to generated PCH file without tmpdir hardcoded is to generated it on a live system. This is way too dangerous, since any mistake in the script or rootcint may destroy / and whole system.

What bothers me is that pch and some headers are located in /etc, especially considering that pch file size is over 100 MB. It can't be removed because it contains dictionaries for ROOT classes and relocation is non-trivial. I contacted upsteam to discuss this, see:
https://groups.cern.ch/group/roottalk/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Froottalk%2FLists%2FArchive%2FROOT-6.02.05%20Headers%20in%20etc&FolderCTID=0x01200200A201AF59FD011C4E9284C43BF0CDA2A4
