### ISSUE TITLE
ipywidgets (and ipython) wrongly depends on wxpython

### ISSUE THREAD

**Issue by kiwifb** [gentoo-science/sci#488]
I cannot see a statement loading `wx` anywhere. I also have a more vanilla install on a mac that is definitely not using `wxpython` since wxwidgets is not there at all and the `ipython-4` notebook is working perfectly.

**Comment by marbre** [comment]
Seems you're right. This was initially imported/moved from the ipython ebuild (<4.0.0). Will be fixed with pull request #489.

**Comment by kiwifb** [comment]
I should have gone directly for pull request myself but it was late and I wanted to leave a record somewhere - not that I would have forgotten with `sage` moving to `ipython-4` and `jupyter` in the next release.

**Comment by marbre** [comment]
@kiwifb No problem, I am aware that it's sometimes too late ;) My comment was just to create a cross reference to the PR.

**Comment by marbre** [comment]
Okay, finally I found that wxpython is still required for ipython ( e.g. by https://github.com/ipython/ipython/blob/master/IPython/lib/inputhook.py and https://github.com/ipython/ipython/blob/master/IPython/lib/inputhookwx.py). Thus, just moving the dependency from ipython to ipywidgets was clearly wrong and the dependency should be moved back to the ipython ebuild.

@suhr If you like, add this to your pull request :) Otherwise, I will commit this after merging the PR.

**Comment by suhr** [comment]
I see. But can *notebooks* work without wxwidgets?

PS: I'll commit a bit later.

**Comment by marbre** [comment]
@suhr This is a good question. Issue #474 indicates that at least **ipython** notebooks can't. I didn't tested juptyer kernels for other languages.

**Comment by suhr** [comment]
Issue #474 says about *ipy*widgets, not *wx*widgets.

**Comment by marbre** [comment]
@shur You're right. Then I don't know. Maybe @kiwifb can comment? My system isn't vanilla and I currently can't break it since I use juptyer for my research. Maybe I'll find the time to setup a new chroot end of the month. In the meanwhile, I suggest to move the dependency from ipywidgets back to ipython.

**Comment by kiwifb** [comment]
I have worked with an `ipython-4` stack on OS X to test it for inclusion in the next release of `sage`. We have `notebook` and `ipywidgets` but no `wxpython` anywhere. Everyone else who tested it didn't see anything wrong with it https://github.com/vbraun/sage/commit/385e949896731d5a5396f856620c1573efd43ad8.
In fact I removed the dependency on `wxpython` in a private overlay yesterday and build and doctested the current head of `sage` in `sage-on-gentoo` and nothing blew up.

It looks to me like the `wxpython` graphics hook are independent of `ipywidgets`. The later looks more about `html` widgets than a a full blown interface.

**Comment by kiwifb** [comment]
Yes looking at it more closely if you want a useflag for `ipywidgets` it needs to be distinct from `wxwidgets`. You can have a `wxpython` app like you have `qt4` app but it has nothing to do with `ipywidgets`. So I think we should keep the `wxwidgets` use flag but make it trigger a dependency on `wxpython` instead - I haven't seen a `qtconsole` equivalent. I don't know if we want to have a new flag for `ipywidgets` or just couple it with the `notebook` like you had done.

**Comment by marbre** [comment]
I suggest to
* (re)add the *wxpython* use flag to `ipython` that pulls in `wxpython` and **not** `ipywidgets`,
* add `ipywidgets` as dependency of `ipython[notebook]`, without any new/additional use flag and
* drop the `wxpython` dependency in `ipywidgets`.

**Comment by marbre** [comment]
Fixed with commit c063b86.
